# Configuraçôes Básicas de como o NGinx se comporta
user www-data; # Define o usuário que o Nginx irá rodar
worker_processes auto; # Define o número de processos de trabalho do Nginx
# "auto" ajusta automaticamente com base no número de núcleos da CPU disponíveis.
pid /run/nginx.pid; # Define o arquivo de PID (Process ID) do Nginx
# É usado para gerenciar o processo principal do servidor.


events { # Lida com conexões de rede e eventos assíncronos.
    worker_connections 1024; # Define o número máximo de conexões simultâneas que cada worker pode lidar.
}

http {
    include       /etc/nginx/mime.types; # Definicão dos tipos MIME para diferentes extensões de arquivo.

    resolver 127.0.0.11 valid=10s ipv6=off; # Define o resolvedor de DNS para o Nginx. Ele resolve nomes de domínio para endereços IP.
    # 127.0.0.11 = Endereço IP do resolvedor DNS interno do Docker. (Disponivel pelo próprio Docker ao criar uma rede bridge)

    server {
        listen ${FRONTEND_INTERNAL_PORT} ssl; # Define a porta que o Nginx irá escutar para conexões HTTPS.
        server_name ${DOMAIN_NAME}; # Define o nome do servidor (domínio) que o Nginx irá responder.

        ssl_certificate     /etc/nginx/ssl/nginx.crt; # Define o caminho para o certificado SSL usado para criptografar as conexões HTTPS.
        ssl_certificate_key /etc/nginx/ssl/nginx.key; # Define o caminho para a chave privada do certificado SSL.
        ssl_protocols       TLSv1.2 TLSv1.3; # Define os protocolos SSL/TLS que o Nginx irá suportar.

        root  /var/www/html; # Define o diretório raiz onde os arquivos do site estão localizados.
        index index.html; # Define o arquivo padrão a ser servido quando um diretório é acessado.

        location / { # Define a configuração para a localização raiz do site.
            # Tenta servir o arquivo solicitado. Se não encontrado, tenta servir um diretório.
            try_files $uri $uri/ /index.html;
        }

        location /api/ { # Define a configuração para a localização /api/ do site.
            set $backend_upstream backend;
            proxy_pass http://$backend_upstream:${BACKEND_INTERNAL_PORT};
            proxy_set_header Host $host;
        }

        location /socket.io/ { # Define a configuração para a localização /socket.io/ do site, que é usada para WebSockets.
            set $backend_upstream backend;
            proxy_pass http://$backend_upstream:${BACKEND_INTERNAL_PORT};
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
